var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0b7q7d_._.js")
R.c("server/chunks/ssr/0ba__next_dist_esm_build_templates_app-page_0br-vwe.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~q70jm._.js")
R.c("server/chunks/ssr/0ba__next_dist_compiled_0gpto_e._.js")
R.c("server/chunks/ssr/0ba__next_dist_0aab~6h._.js")
R.c("server/chunks/ssr/0ba__next_dist_07r0x16._.js")
R.c("server/chunks/ssr/node_modules__pnpm_0v_ul67._.js")
R.c("server/chunks/ssr/0ba__next_dist_client_components_0fiibei._.js")
R.c("server/chunks/ssr/0ba__next_dist_client_components_builtin_forbidden_0rtura..js")
R.c("server/chunks/ssr/0ba__next_dist_client_components_builtin_unauthorized_00sfxcq.js")
R.c("server/chunks/ssr/_next-internal_server_app__not-found_page_actions_0eq97pa.js")
R.m(788643)
module.exports=R.m(788643).exports
