name: Build and Deploy Payload to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build application
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
        run: npm run build

      - name: Verify build
        run: |
          echo "Project Files:"
          ls -la

          echo "Checking .next"
          ls -la .next

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          include-hidden-files: true
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Verify downloaded files
        run: |
          ls -la
          ls -la .next

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AC822D5CB70B41CF9C23F40839EF15F9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DC178793BF6741E98867F9301771736E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3E9C3B2E87EE4186881480C28A2226C0 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: bnoon-payload
          package: .
